Change examples to use genezio latest features.
Genez-io/genezio-examples pull request #32
Opened 2023-10-25 06:51 UTC by vladiulianbogdan

2023-10-25 06:59 UTC, radu1122 approved these changes

2023-10-25 06:59 UTC, radu1122 commented on javascript/blockchain/server/genezio.yaml
>  scripts:
Shouldn't be one tab on the left?

2023-10-25 06:59 UTC, radu1122 commented on javascript/cron/genezio.yaml
>  name: cron-example
Same here

2023-10-25 13:01 UTC, andreia-oca requested changes
I have a few overall comments.

Two of the projects are still outdated `javascript/hello-world` and `javascript/todo-list-sql`.

The READMEs are outdated.

There is an old sdk directory that is leftover in the codebase:
```
./javascript/todo-list-vue/client/src/sdk
```

And some build directories that should also be cleaned:
```
./javascript/todo-list-vue/client/build
./typescript/webhook/client/build
```

2023-10-26 12:07 UTC, andreia-oca commented on javascript/todo-list-sql/client/genezio.yaml
> +  path: ../client/build
```suggestion
  path: ./build
```

2023-10-26 12:07 UTC, andreia-oca commented on typescript/getting-started/client/genezio.yaml
> +  path: ../client/build
```suggestion
  path: ./build
```

2023-10-26 12:07 UTC, andreia-oca commented on typescript/quiz-app-prisma/client/genezio.yaml
> +  path: ../client/build
```suggestion
  path: ./build
```

2023-11-06 11:17 UTC, merged