Add the source code for the shopping cart example.
Genez-io/genezio-examples pull request #34
Opened 2023-11-07 19:21 UTC by andreia-oca

This PR adds a shopping cart example built with Nodejs, React and Upstash Redis.

This example will be a project companion for an article on the genezio blog.

2023-11-07 20:22 UTC, costinsin requested changes
This project does not deploy the frontend. I think this is a bug in the CLI because it checks for the `frontend` field to exist in the configuration, but does not take into consideration the `workspace` field. https://github.com/Genez-io/genezio/blob/2e763239e1517830b11e45997330abc2a2c60ca6/src/commands/deploy.ts#L596

Can you please investigate what happens wrong here and file a bug. For now, the solution would be to add the `frontend` field in the configuration, but I would argue this should not be a fix because this is a backwards compatible feature and we don't want to encourage this.

[![soundsgooddoesntwork](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/WjlTemxb6oA4PgZFmj08/b7021b3d-4537-4717-ba09-8bf26ccc37df/soundsgooddoesntwork.gif)](https://app.graphite.dev/macros/Genez-io)

2023-11-07 20:24 UTC, costinsin commented
I have attached you my logs so you can better see that the frontend does not get deployed.

```
$ genezio
Loading...✅

genezio.yaml file found in current directory. Running deploy command...
Bundling your code...✅

Deploying your backend project to genezio infrastructure...
Uploading ShoppingCartService: ████████████████████████████████████████ | 100% | 0s
Checking your credentials...✅
Deploying...crossing our fingers...✅
Doing the final touch-ups...✅

Your code was deployed and the SDK was successfully generated!

   ╭──────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                          │
   │   To install the SDK in your client, run this command in your client's root:             │
   │   npm install @genezio-sdk/getting-started-upstash_us-east-1@1.0.0-prod                  │
   │                                                                                          │
   │   Then import your classes like this:                                                    │
   │   import { ShoppingCartService } from "@genezio-sdk/getting-started-upstash_us-east-1"   │
   │                                                                                          │
   ╰──────────────────────────────────────────────────────────────────────────────────────────╯

Your backend project has been deployed and is available at https://app.genez.io/project/bbac0eac-1828-45ae-b66c-5fc428fd26ea/85fe8403-bed6-4fcd-8f5d-d9c870f3a4ba
Deploying your frontend to genezio infrastructure...
No frontend entry in genezio configuration file.
```

2023-11-08 11:24 UTC, andreia-oca commented
> This project does not deploy the frontend. I think this is a bug in the CLI because it checks for the `frontend` field to exist in the configuration, but does not take into consideration the `workspace` field. https://github.com/Genez-io/genezio/blob/2e763239e1517830b11e45997330abc2a2c60ca6/src/commands/deploy.ts#L596
> 
> Can you please investigate what happens wrong here and file a bug. For now, the solution would be to add the `frontend` field in the configuration, but I would argue this should not be a fix because this is a backwards compatible feature and we don't want to encourage this.


You are right, the frontend could not be deployed. This is not a bug, though. I was misusing the genezio workspace feature.
I fixed it in this project.

You can try to redeploy the project. It should work now.

2023-11-08 11:26 UTC, costinsin approved these changes

2023-11-08 11:33 UTC, costinsin requested changes
https://github.com/Genez-io/genezio-examples/assets/56958521/3cf40949-6376-4b40-92be-0f7e85ccae2c


My frontend crashes when I click the cart button.
Check it youtself: https://salmon-vulnerable-lark.dev.app.genez.io/

2023-11-13 10:21 UTC, andreia-oca commented
Indeed this was a bug on our end. We did not handle Upstash Redis instances with TSL enabled correctly.

I did a hotfix and now the problem is fixed. Please delete the environments variables inside the Upstash integration page by hitting the `Delete` button and re-enable the integration. This should fix the connection to the Redis database and your project should work.

There is no need to redeploy, just re-set the env var for Upstash,

2023-11-13 10:23 UTC, costinsin approved these changes
Nice catch with the Upstash global databases!

2023-11-13 10:27 UTC, radu1122 commented on typescript/shopping-cart/client/src/ProductCard.tsx
> +    ShoppingCartService.addItemToCart(token, product.title)
await here

2023-11-13 10:27 UTC, radu1122 commented on typescript/shopping-cart/client/src/ProductCard.tsx
> +      <button className="buy-button" onClick={handleBuyClick}>
here I would do: `onClick={(e) => handleBuyClick(e)}

2023-11-13 10:30 UTC, radu1122 commented on typescript/shopping-cart/client/src/ProductCard.tsx
> +  const handleBuyClick = () => {
const handleBuyClick = (e: any) => {
   e.preventDefault();

2023-11-13 10:54 UTC, andreia-oca commented
I have received a live feedback:
- to use `reactstrap` for minifying the css [1]
- to add states on the buttons to show there is work happening in the background:
  - for "Buy" button
  - for "Delete" buton
  - for "Clear cart" button

[1] https://reactstrap.github.io/

2023-11-14 14:49 UTC, adriangeorge commented on typescript/shopping-cart/client/src/App.tsx
> +
maybe a cart item counter state could be added here, it would add some nice visual feedback when pressing the add to cart button and it would naturally make the user click on the cart after seeing the component update

```js
const [cartCounter, setCartCounter] = useState(0);
```

this counter would be updated at every operation, maybe using a reduce to add all the items in the cart

2023-11-14 14:50 UTC, adriangeorge commented on typescript/shopping-cart/client/src/App.tsx
> +            <ShoppingCartIcon />
here i'd add the cart counter alongisde the icon

```js
        <button className="cart-button" onClick={toggleCartModal}>
            <p>{cartCounter}</p>
            <ShoppingCartIcon />
        </button>
```

2023-11-14 14:51 UTC, adriangeorge commented on typescript/shopping-cart/client/src/App.tsx
> +
![image](https://github.com/Genez-io/genezio-examples/assets/41837216/6036f8f2-6068-4f08-93f6-828d612224ed)

2023-11-15 09:08 UTC, adriangeorge approved these changes

2023-11-15 22:49 UTC, merged