Getting started javascript client modified to vite
Genez-io/genezio-examples pull request #44
Opened 2023-12-12 15:03 UTC by Virgil993

2023-12-12 15:39 UTC, costinsin requested changes
Please also change the readme in the workspace folder. It now states that the client can be started with 'npm start' which is not true. Replace with 'npm run dev'

2023-12-12 15:39 UTC, costinsin commented on javascript/getting-started/client/README.md
> +# React + Vite
Change the title to getting started

2023-12-12 15:39 UTC, costinsin commented on javascript/getting-started/client/index.html
> +    <title>Vite + React</title>
Change the title

2023-12-12 15:39 UTC, costinsin commented on javascript/getting-started/client/public/vite.svg
Delete this, as you don't use it anymore

2023-12-12 15:39 UTC, costinsin commented on javascript/getting-started/client/src/assets/react.svg
Delete this as you don't use it anymore

2023-12-13 07:31 UTC, vladiulianbogdan commented on javascript/getting-started/client/package.json
> +    "@genezio-sdk/getting-started-genezio_us-east-1": "^1.0.0-prod",
this dependency should be removed otherwise if the user runs `genezio local` it will fail

2023-12-14 13:41 UTC, stefandarius approved these changes

2023-12-14 13:41 UTC, merged